### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by jesulim** [jesulim/portfolio#1]
- [ ] Arreglar el stack tecnologico
- [ ] Anadir los proyectos realizados
- [ ] #2
- [ ] Añadir modo oscuro
